### Requests which reads the data of the note "TestNote"
GET http://{{host}}/note/read/TestNote HTTP/1.1

### Requests which reads the data of the note "Another one"
GET http://{{host}}/note/read/Another one HTTP/1.1
