openapi: 3.0.0
info:
  title: Rocket Notes Api
  description: Api for remote note management
  version: 0.2.0

servers:
  - url: http://localhost:5000

paths:
  /counter:
    $ref: "./paths/count.yaml#/counter"
  /counter/increment:
    $ref: "./paths/count.yaml#/increment"
  /note/read/{title}:
    $ref: "./paths/note.yaml#/read"
  /note/listAll:
    $ref: "./paths/note.yaml#/listAll"
  /note/delete/{title}:
    $ref: "./paths/note.yaml#/delete"
  /note/create:
    $ref: "./paths/note.yaml#/create"